let num1 = 51;
let num2 = 21;
console.log(`Addition: ${num1 + num2}`);
console.log(`Subtraction: ${num1 - num2}`);
console.log(`Subtraction: ${num2 - num1}`);
console.log(`Multiplication: ${num1 * num2}`);
console.log(`Division: ${num1 / num2}`);
console.log(`Division: ${num2 / num2}`);
console.log(`Remainder: ${num1 % num2}`);
